# -*- coding: utf-8 -*-
"""API_Final.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1u8q2VaA7nPkobD_IEHrmEED-TEIDyfbv
"""

from fastapi import FastAPI, HTTPException
from pydantic import BaseModel, Field
from typing import Literal
import joblib
import numpy as np
import pandas as pd

app = FastAPI(
    title="Bucknell Lending Club Loan Risk Assessment API",
    description="API for predicting loan repayment propensity, pessimistic annualized return, and providing a loan recommendation."
)

avg_return_fully_paid = 4.612149501658192
avg_return_not_fully_paid = -12.537793299762876
custom_cutoff_logreg = 0.55

combined_15_features = [
    'credit_age', 'int_rate', 'verification_status_Source Verified', 'term_num',
    'fico_avg', 'loan_amnt', 'home_ownership_RENT', 'home_ownership_MORTGAGE',
    'revol_util', 'grade_B', 'log_annual_inc', 'grade_D', 'grade_C', 'grade_E', 'dti'
]

logreg_model = joblib.load("logistic_regression_model.pkl")
lasso_model = joblib.load("lassocv_regressor_model.pkl")
scaler = joblib.load("scaler_reduced.pkl")

class LoanApplication(BaseModel):
    loan_amnt: float = Field(..., ge=500, le=40000, description="Loan Amount requested (USD)")
    int_rate: float = Field(..., ge=0.1, le=30.0, description="Interest Rate (%)")
    fico_avg: int = Field(..., ge=300, le=850, description="Average FICO Score")
    dti: float = Field(..., ge=0.0, le=50.0, description="Debt-to-Income Ratio (%)")
    revol_util: float = Field(..., ge=0.0, le=100.0, description="Revolving Line Utilization (%)")
    annual_inc: float = Field(..., ge=10000, le=1000000, description="Annual Income (USD)")
    credit_age: float = Field(..., ge=0.1, le=60.0, description="Credit History Length (Years)")
    term_num: Literal[36, 60] = Field(..., description="Loan Term in months")
    home_ownership: Literal['MORTGAGE', 'RENT', 'OWN', 'ANY', 'OTHER', 'NONE'] = Field(..., description="Home Ownership Status")
    grade: Literal['A', 'B', 'C', 'D', 'E', 'F', 'G'] = Field(..., description="Loan Grade (Bucknell Lending Club's internal risk grade)")
    verification_status: Literal['Verified', 'Source Verified', 'Not Verified'] = Field(..., description="Income Verification Status")

@app.get("/", tags=["Status"])
def home():
    return {"message": "Bucknell Lending Club Loan Risk Assessment API is running"}

@app.post("/predict", tags=["Predictions"])
def predict(data: LoanApplication):
    input_data_dict = {feature: 0 for feature in combined_15_features}

    input_data_dict['loan_amnt'] = data.loan_amnt
    input_data_dict['int_rate'] = data.int_rate
    input_data_dict['fico_avg'] = data.fico_avg
    input_data_dict['dti'] = data.dti
    input_data_dict['revol_util'] = data.revol_util
    input_data_dict['credit_age'] = data.credit_age
    input_data_dict['term_num'] = data.term_num

    input_data_dict['log_annual_inc'] = np.log1p(data.annual_inc)

    if data.home_ownership == 'RENT':
        input_data_dict['home_ownership_RENT'] = 1
    elif data.home_ownership == 'MORTGAGE':
        input_data_dict['home_ownership_MORTGAGE'] = 1

    if data.grade == 'B':
        input_data_dict['grade_B'] = 1
    elif data.grade == 'C':
        input_data_dict['grade_C'] = 1
    elif data.grade == 'D':
        input_data_dict['grade_D'] = 1
    elif data.grade == 'E':
        input_data_dict['grade_E'] = 1

    if data.verification_status == 'Source Verified':
        input_data_dict['verification_status_Source Verified'] = 1

    input_df = pd.DataFrame([input_data_dict], columns=combined_15_features)

    scaled_input_df = scaler.transform(input_df)

    p_fully_paid = logreg_model.predict_proba(scaled_input_df)[:, 1][0]
    p_not_fully_paid = 1 - p_fully_paid

    predicted_ret_PESS = lasso_model.predict(scaled_input_df)[0]

    expected_ret_PESS = (p_fully_paid * avg_return_fully_paid) + \
                        (p_not_fully_paid * avg_return_not_fully_paid)

    if p_fully_paid >= custom_cutoff_logreg and expected_ret_PESS > 0:
        recommended_action = "APPROVE"
    else:
        recommended_action = "REJECT"

    return {
        "fully_paid_propensity": round(float(p_fully_paid), 4),
        "predicted_pessimistic_annualized_return": round(float(predicted_ret_PESS), 4),
        "expected_pessimistic_annualized_return": round(float(expected_ret_PESS), 4),
        "recommended_action": recommended_action
    }